true = "真的"
false = "假的"
bool = "逻辑"
break = "循环终止"
elif = "否则如果"
else = "否则"
for = "计数循环"
func = "函数"
if = "如果"
plug = "导入"
null = "空"
num = "数存"
return = "返回"
static = "静态"
string = "字节集"
text = "文本"
while = "循环"
